apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 3-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  zzz_deprecatedclustername: ""
  managedfields: []
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: testgary22
      name: testgary22
    spec:
      replicas: ${{COMMON_REPLICAS}}
      selector:
        matchLabels:
          move2kube.konveyor.io/service: testgary22
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            move2kube.konveyor.io/service: testgary22
          name: testgary22
        spec:
          containers:
            - image: quay.io/3/testgary22:latest
              imagePullPolicy: Always
              name: testgary22
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: testgary22
      name: testgary22
    spec:
      ports:
        - name: port-8080
          port: 8080
          targetPort: 8080
      selector:
        move2kube.konveyor.io/service: testgary22
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: "3"
      name: "3"
    spec:
      rules:
        - host: 3.com
          http:
            paths:
              - backend:
                  service:
                    name: testgary22
                    port:
                      name: port-8080
                path: /testgary22
                pathType: Prefix
    status:
      loadBalancer: {}
parameters:
  - name: COMMON_REPLICAS
    value: "2"
