# From https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/skeletons/tekton/tekton/pipelinerun.yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testgary22-5c0e983
  namespace: orchestrator-gitops
  labels:
    backstage.io/kubernetes-id: testgary22-ci
spec:
  params:
    - name: gitUrl
      value: git@github.com:orchestrator-test/test-gary-22.git
    - name: gitOpsUrl
      value: git@github.com:orchestrator-test/test-gary-22-gitops.git
    - name: workflowId
      value: testgary22
    - name: convertToFlat
      value: 'true'
    - name: quayOrgName
      value: rhdh-orchestrator-test
    - name: quayRepoName
      value: orchestrator-qe-ci
  pipelineRef:
    name: workflow-deployment
  workspaces:
    - name: workflow-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: workflow-gitops
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
    - name: ssh-creds
      secret:
        secretName: git-ssh-credentials